Ext.define('Extidi.sistema.dinamico.constantes',{
    singleton:true,
    URL_MODELO_FORMULARIO: Extidi.BASE_PATH+"index.php/dinamico/modeloFormulario",
    URL_MODELO_ACCIONES_ADICIONALES: Extidi.BASE_PATH+"index.php/dinamico/modeloAccionesAdicionales",
    URL_MODELO_FORMULARIO_FILTRO: Extidi.BASE_PATH+"index.php/dinamico/modeloFormularioFiltro",
    URL_MODELO_GRILLA: Extidi.BASE_PATH+"index.php/dinamico/modeloGrilla",
    URL_LISTADO_GRILLA: Extidi.BASE_PATH+"index.php/dinamico/listadoGrilla",
    URL_VALOR_FORANEO: Extidi.BASE_PATH+"index.php/dinamico/valorForaneo",
    URL_CARGAR_MODAL: Extidi.BASE_PATH+"index.php/dinamico/cargarModal",
    URL_GUARDAR: Extidi.BASE_PATH+"index.php/dinamico/guardar",
    URL_ELIMINAR: Extidi.BASE_PATH+"index.php/dinamico/eliminar",
    URL_ACTIVAR: Extidi.BASE_PATH+"index.php/dinamico/activar",
    URL_INACTIVAR: Extidi.BASE_PATH+"index.php/dinamico/inactivar",
    URL_EXCEL: Extidi.BASE_PATH+"index.php/dinamico/excel",
    URL_PDF: Extidi.BASE_PATH+"index.php/dinamico/pdf",
    URL_CSV: Extidi.BASE_PATH+"index.php/dinamico/csv",
    URL_IMPRIMIR: Extidi.BASE_PATH+"index.php/dinamico/imprimir",
    URL_PLANTILLA: Extidi.BASE_PATH+"index.php/dinamico/plantilla",
    URL_IMPORTAR: Extidi.BASE_PATH+"index.php/dinamico/importar",
    URL_CARGAR_ARCHIVOS: Extidi.BASE_PATH+"index.php/dinamico/cargar_archivos",
    URL_SUBIR_ARCHIVO: Extidi.BASE_PATH+"index.php/dinamico/subir_archivo"
});